### ISSUE TITLE
week 01 回覆

### ISSUE THREAD

**Issue by azole** [Sebastian-0912/git-practice#1]
不用叫教授，叫我小賴，最多叫我小賴老師就可以了。

作業做得不錯，在觀察紀錄中，是否可以更明確指出你觀察到什麼變化，例如「.git/objects多了一個e6」，這是你有分享的部分，但每一步應該都可以紀錄你確實觀察到的變化是什麼。

另外，透過這些觀察，你有沒有自己總結出什麼結論來？例如這些觀察有沒有佐證了你閱讀到的、對 git 底層的那些知識？也就是把觀察紀錄的部分跟上方的五個問題交互再一起看？

最後是，除了我在作業單上的提問外，你自己有沒有對 git 有其他的「好奇」？

**Comment by Sebastian-0912** [comment]
好的，謝謝老師！我會多研究以後再回覆老師的問題！非常謝謝老師的指導！

**Comment by azole** [comment]
謝謝你的回覆，透過這門課來持續練習做出自己的實驗，會愈來愈強的，加油

如果沒有其他需要跟我討論的事，這個 issue 可以 close 了。
